#!/bin/sh
# Change server password

yum -y install expect
echo '#!/usr/bin/expect
set username root
set password PASSWORD
spawn passwd $username
expect "*password:"
send "$password\r"
expect "*password:"
send "$password\r"
expect "*successfully" {exit 12}
expect eof
exit 13
'> /root/passwd.expect
expect /root/passwd.expect
rm -f /root/passwd.expect
